/**
 * This file is a collection of enums for values in the base game.
 */

/**
 * Fertilities
 * @readonly
 * @enum {string} Anno2070.Fertility
 */
export const Fertility = {
  "NoFertility": "NoFertility",
  "Wood": "Wood",
  "SugarBeet": "SugarBeet",
  "Rice": "Rice",
  "Tea": "Tea",
  "Vegetables": "Vegetables",
  "Truffles": "Truffles",
  "Fruits": "Fruits",
  "Grain": "Grain",
  "Corn": "Corn",
  "Coffee": "Coffee",
  "Grapes": "Grapes",
  "Algae": "Algae",
  "Diamonds": "Diamonds",
  "ManganeseNodules": "ManganeseNodules",
  "Wildcard": "Wildcard",
  "BlackSmoker": "BlackSmoker",
  "BlackSmokerGold": "BlackSmokerGold",
  "BlackSmokerCopper": "BlackSmokerCopper",
  "BlackSmokerUranium": "BlackSmokerUranium",
  "BlackSmokerIron": "BlackSmokerIron",
  "Sponges": "Sponges",
};

/**
 * Products
 * @readonly
 * @enum {string} Anno2070.Product
 */
export const Product = {
  "NoProduct": "NoProduct",
  "BuildingModules": "BuildingModules",
  "Tools": "Tools",
  "Wood": "Wood",
  "Glass": "Glass",
  "Concrete": "Concrete",
  "Steel": "Steel",
  "Carbon": "Carbon",
  "Fish": "Fish",
  "ComfortFood": "ComfortFood",
  "HealthFood": "HealthFood",
  "TVDinner": "TVDinner",
  "LuxuryMeal": "LuxuryMeal",
  "FunctionalFood": "FunctionalFood",
  "Tea": "Tea",
  "HealthDrink": "HealthDrink",
  "Liquor": "Liquor",
  "Champagne": "Champagne",
  "EnergyDrink": "EnergyDrink",
  "Toys": "Toys",
  "Jewelry": "Jewelry",
  "Pharmaceuticals": "Pharmaceuticals",
  "Communicator": "Communicator",
  "Holographer": "Holographer",
  "HomeRobot": "HomeRobot",
  "Coal": "Coal",
  "Granulate": "Granulate",
  "IronOre": "IronOre",
  "Iron": "Iron",
  "Copper": "Copper",
  "Limestone": "Limestone",
  "Sand": "Sand",
  "RawOil": "RawOil",
  "Oil": "Oil",
  "Microchips": "Microchips",
  "Sugar": "Sugar",
  "ManganeseNodules": "ManganeseNodules",
  "RareEarths": "RareEarths",
  "Diamonds": "Diamonds",
  "Uranium": "Uranium",
  "Meat": "Meat",
  "SuperFlavor": "SuperFlavor",
  "Explosives": "Explosives",
  "Lobster": "Lobster",
  "Truffles": "Truffles",
  "Grapes": "Grapes",
  "GoldNuggets": "GoldNuggets",
  "Gold": "Gold",
  "OmegaAcids": "OmegaAcids",
  "SecretIngredient": "SecretIngredient",
  "Soy": "Soy",
  "Vegetables": "Vegetables",
  "Fruits": "Fruits",
  "Milk": "Milk",
  "Grain": "Grain",
  "Flour": "Flour",
  "Corn": "Corn",
  "Biopolymer": "Biopolymer",
  "Caffeine": "Caffeine",
  "Algae": "Algae",
  "FuleRod": "FuleRod",
  "Kerosene": "Kerosene",
  "Weapons": "Weapons",
  "HeavyWeapons": "HeavyWeapons",
  "AdvancedWeapons": "AdvancedWeapons",
  "CoralExtract": "CoralExtract",
  "LaboratoryInstruments": "LaboratoryInstruments",
  "NeuroImplants": "NeuroImplants",
  "BioSuites": "BioSuites",
  "Enzymes": "Enzymes",
  "Platinum": "Platinum",
  "Sponges": "Sponges",
  "Lithium": "Lithium",
  "EnergyCells": "EnergyCells",
  "Exoskeleton": "Exoskeleton",
  "Coral": "Coral"
};

/**
 * I thinks these are the milestones for getting new build options
 * @readonly
 * @enum {string} Anno2070.Product
 */
export const IntermediateLevel = {
  "NoIntermediate":"NoIntermediate",
  "IntermediateEcos":"IntermediateEcos",
  "IntermediateEcos1":"IntermediateEcos1",
  "IntermediateEcos2":"IntermediateEcos2",
  "IntermediateEcos3":"IntermediateEcos3",
  "IntermediateEcos4":"IntermediateEcos4",
  "IntermediateTycoons":"IntermediateTycoons",
  "IntermediateTycoons1":"IntermediateTycoons1",
  "IntermediateTycoons2":"IntermediateTycoons2",
  "IntermediateTycoons3":"IntermediateTycoons3",
  "IntermediateTycoons4":"IntermediateTycoons4",
  "IntermediateTechs":"IntermediateTechs",
  "IntermediateTechs1":"IntermediateTechs1",
  "IntermediateTechs2":"IntermediateTechs2",
  "Intermediate1":"Intermediate1",
  "Intermediate2":"Intermediate2",
  "Intermediate3":"Intermediate3",
  "Intermediate4":"Intermediate4",
  "IntermediateTools":"IntermediateTools",
  "IntermediateTVDinner":"IntermediateTVDinner",
  "IntermediateHealthFood":"IntermediateHealthFood",
  "IntermediateLuxuryMeal":"IntermediateLuxuryMeal",
  "IntermediateComfortFood":"IntermediateComfortFood",
  "IntermediateFunctionalFood":"IntermediateFunctionalFood",
  "IntermediateTea":"IntermediateTea",
  "IntermediateLiquor":"IntermediateLiquor",
  "IntermediateHealthDrink":"IntermediateHealthDrink",
  "IntermediateChampagne":"IntermediateChampagne",
  "IntermediateEnergyDrink":"IntermediateEnergyDrink",
  "IntermediateCommunicator":"IntermediateCommunicator",
  "IntermediateHolographer":"IntermediateHolographer",
  "IntermediateHomeRobot":"IntermediateHomeRobot",
  "IntermediateToys":"IntermediateToys",
  "IntermediateJewelry":"IntermediateJewelry",
  "IntermediatePharmaceuticals":"IntermediatePharmaceuticals",
  "IntermediateSand":"IntermediateSand",
  "IntermediateOil":"IntermediateOil",
  "IntermediateUranium":"IntermediateUranium",
  "IntermediateDiamond":"IntermediateDiamond",
  "IntermediateMangan":"IntermediateMangan",
  "IntermediateSugar":"IntermediateSugar",
  "IntermediateLimestone":"IntermediateLimestone",
  "IntermediateChips":"IntermediateChips",
  "IntermediateWeapons":"IntermediateWeapons",
  "IntermediateHeavyWeapons":"IntermediateHeavyWeapons",
  "IntermediateAdvancedWeapons":"IntermediateAdvancedWeapons",
  "IntermediateMissileLaunching":"IntermediateMissileLaunching",
  "IntermediateCogeneration":"IntermediateCogeneration",
  "IntermediateSolarTower":"IntermediateSolarTower",
  "IntermediateNuclearPower":"IntermediateNuclearPower",
  "IntermediateAirport":"IntermediateAirport",
  "IntermediateContainerHarbour":"IntermediateContainerHarbour",
  "IntermediateCasino":"IntermediateCasino",
  "IntermediateConcertHall":"IntermediateConcertHall",
  "IntermediateAcademy":"IntermediateAcademy",
  "IntermediateMinistryOfTruth":"IntermediateMinistryOfTruth",
  "IntermediateEducationNetwork":"IntermediateEducationNetwork",
  "IntermediateBroadcastingStation":"IntermediateBroadcastingStation",
  "IntermediateCorporateHeadquarter":"IntermediateCorporateHeadquarter",
  "IntermediateCongressCenter":"IntermediateCongressCenter",
  "IntermediateRubbleMine":"IntermediateRubbleMine",
  "IntermediateWasteIncinerator":"IntermediateWasteIncinerator",
  "IntermediateRiverfilterplant":"IntermediateRiverfilterplant",
  "IntermediateOzonemaker":"IntermediateOzonemaker",
  "IntermediateFinalStorage":"IntermediateFinalStorage",
  "IntermediateBlackSmoker":"IntermediateBlackSmoker",
  "IntermediateLaboratory":"IntermediateLaboratory",
  "IntermediateScience1":"IntermediateScience1",
  "IntermediateScience2":"IntermediateScience2",
  "IntermediateScience3":"IntermediateScience3",
  "IntermediateScience4":"IntermediateScience4",
  "IntermediateFire":"IntermediateFire",
  "IntermediateDisease":"IntermediateDisease",
  "IntermediateCrime":"IntermediateCrime",
  "IntermediateNever":"IntermediateNever",
  "IntermediateTechs3":"IntermediateTechs3",
  "IntermediateTransmission":"IntermediateTransmission",
  "IntermediateGeothermical":"IntermediateGeothermical",
  "IntermediateDefencePlatform":"IntermediateDefencePlatform",
  "IntermediateCoralExtract":"IntermediateCoralExtract",
  "IntermediateLaboratoryInstruments":"IntermediateLaboratoryInstruments",
  "IntermediateNeuroImplants":"IntermediateNeuroImplants",
  "IntermediateBioSuites":"IntermediateBioSuites",
  "IntermediateTechsMonument1":"IntermediateTechsMonument1",
  "IntermediateTechsMonument2":"IntermediateTechsMonument2",
  "IntermediateTechsMonument3":"IntermediateTechsMonument3",
  "IntermediateTechsMonument4":"IntermediateTechsMonument4",
  "IntermediateTownAcquisition":"IntermediateTownAcquisition"
};

/**
 * Building GUIDs
 * @readonly
 * @enum {Number} Anno2070.BuildingGUID
 */
export const Building = {
  "tycoon_worker_residence": 10021,
  "tycoon_citizen_residence": 10076,
  "tycoon_executive_residence": 10116,
  "tycoon_leader_residence": 10118,
  "tycoon_ruin_residence": 10221,
  "town_center_tycoons": 10257,
  "casino": 10147,
  "ministry_of_truth": 10051,
  "corporate headquarter": 10026,
  "monument_unfinished1_tycoons": 10214,
  "monument_unfinished2_tycoons": 10215,
  "monument_unfinished3_tycoons": 10216,
  "monument_tycoons": 10217,
  "flavor_lab": 10150,
  "meatfactory": 10022,
  "food_supply_factory": 10152,
  "lobster_farm": 10153,
  "truffle_farm": 10154,
  "gourmet_factory": 10156,
  "distillery": 10046,
  "champagne_cellar": 10158,
  "vineyard": 10157,
  "oil_driller": 10149,
  "plastic_factory": 10159,
  "gold_refinery": 10161,
  "gold_smeltery": 10162,
  "jewelry_manufactory": 10163,
  "fat_factory": 10164,
  "chemical_plant": 10166,
  "pharmaceutical_factory": 10168,
  "excavator": 10024,
  "steelwork": 10057,
  "heavy_arsenal": 10081,
  "explosive_factory": 10093,
  "concrete_factory": 10148,
  "fuel_assembly_factory": 10053,
  "basalt_crusher": 10261,
  "meatfactory_field": 10023,
  "flavor_lab_field": 10151,
  "flavor_lab_field_row": 10241,
  "truffle_farm_field": 10155,
  "distillery_field": 10047,
  "distillery_field_row": 10242,
  "vineyard_field": 10236,
  "vineyard_field_row": 10243,
  "fat_factory_field": 10165,
  "coalpowerplant": 10025,
  "nuclearpowerplant": 10050,
  "nuclearpowerplant_destroyed": 10270,
  "ark_tycoons": 10084,
  "shipyard_tycoons": 10096,
  "missile_launching_platform": 10113,
  "final_storage": 10169,
  "waste_incinerator": 10170,
  "deacidification_station": 10267,
  "depot": 10275,
  "supply_01": 10276,
  "supply_02": 10277,
  "supply_03": 10278,
  "tanks_01": 10279,
  "tanks_02": 10280,
  "tanks_03": 10281,
  "ecos_pioneer_residence": 10011,
  "ecos_villager_residence": 10013,
  "ecos_builder_residence": 10119,
  "ecos_creator_residence": 10117,
  "ecos_ruin_residence": 10222,
  "town_center_ecos": 10229,
  "concert_hall": 10171,
  "education_network": 10121,
  "congress_center": 10172,
  "monument_unfinished1_ecos": 10210,
  "monument_unfinished2_ecos": 10211,
  "monument_unfinished3_ecos": 10212,
  "monument_ecos": 10213,
  "vegetable_farm": 10012,
  "rice_farm": 10174,
  "health_food_factory": 10176,
  "grain_farm": 10177,
  "water_mill": 10179,
  "bakery": 10180,
  "tea_plantation": 10048,
  "fruit_plantation": 10181,
  "dairy_farm": 10183,
  "health_drink_factory": 10185,
  "communicator_factory": 10186,
  "holograph_factory": 10187,
  "corn_farm": 10188,
  "biopolymer_factory": 10190,
  "robot_factory": 10191,
  "treefarm": 10027,
  "saw_mill": 10037,
  "glassworks": 10114,
  "rubble_recycler": 10102,
  "vegetable_farm_field": 10019,
  "vegetable_farm_field_row": 10020,
  "rice_farm_field": 10175,
  "rice_farm_field_row": 10244,
  "grain_farm_field": 10178,
  "grain_farm_field_row": 10245,
  "tea_plantation_field": 10049,
  "tea_plantation_field_row": 10246,
  "fruit_plantation_field": 10182,
  "fruit_plantation_field_row": 10247,
  "dairy_farm_field": 10184,
  "corn_farm_field": 10189,
  "corn_farm_field_row": 10248,
  "rubble_recycler_field": 10268,
  "wind_park": 10029,
  "offshore_wind_park": 10082,
  "cogeneration_power_station": 10173,
  "solar_tower": 10070,
  "solar_tower_field": 10071,
  "monitoring_station": 10192,
  "weather_control_base": 10193,
  "river_filter_plant": 10123,
  "ozone_maker_base": 10061,
  "mobile_shield_generator": 10089,
  "shipyard_ecos": 10094,
  "ark_ecos": 10095,
  "anti_aircraft_site": 10099,
  "eden_line_green_house": 10272,
  "eden_line_plaza": 10273,
  "eden_line_rainwater_depot": 10274,
  "techs_laborant_residence": 10088,
  "techs_scientist_residence": 10209,
  "techs_ruin_residence": 10223,
  "techs_laboratory": 10077,
  "town_center_techs": 10256,
  "broadcasting_station": 10126,
  "algae_farm": 10031,
  "functional_food_factory": 10194,
  "coffee_plantation": 10195,
  "energy_drink_factory": 10197,
  "fuel_factory": 10086,
  "advanced_arsenal": 10100,
  "recycling_station": 10108,
  "carbon_factory": 10112,
  "algaefarm_field": 10032,
  "coffee_plantation_field": 10196,
  "coffee_plantation_field_row": 10249,
  "sea_current_turbine": 10010,
  "hydroelectric_powerplant": 10087,
  "techs_academy": 10078,
  "techs_submarine_base": 10079,
  "ark_techs": 10122,
  "ark_father_techs": 10264,
  "underwater_defence_battery": 10125,
  "airport": 10127,
  "fishery": 10045,
  "sugar_beet_plantation": 10198,
  "iron_mine": 10054,
  "iron_smeltery": 10055,
  "tool_factory": 10056,
  "coal_mine": 10098,
  "copper_mine": 10200,
  "uranium_mine": 10052,
  "sand_extractor": 10080,
  "limestone_quarry": 10083,
  "chip_factory": 10201,
  "arsenal": 10120,
  "oilrig": 10075,
  "oil_refinery": 10092,
  "manganese_miner": 10220,
  "manganese_harvesting_station": 10202,
  "diamond_harvesting_station": 10204,
  "black_smoker_miner": 10239,
  "black_smoker_miner_gold": 10206,
  "black_smoker_miner_copper": 10207,
  "black_smoker_miner_uranium": 10208,
  "black_smoker_miner_iron": 10269,
  "smelting_works": 10262,
  "sugar_beet_plantation_field": 10199,
  "sugar_beet_plantation_field_row": 10271,
  "diamond_harvesting_field": 10226,
  "warehouse": 10035,
  "warehouse2": 10063,
  "warehouse3": 10064,
  "markethouse": 10001,
  "markethouse2": 10065,
  "markethouse3": 10066,
  "underwater warehouse": 10033,
  "underwater warehouse2": 10067,
  "underwater warehouse3": 10237,
  "underwater markethouse": 10238,
  "ark": 10034,
  "hospital": 10128,
  "police_station": 10129,
  "fire_station": 10130,
  "port_authority": 10110,
  "harboursystem": 10044,
  "harbourprops": 10074,
  "overharbour_props": 300010,
  "harbour_defence_turret": 10101,
  "advanced_defence_turret": 10124,
  "container_harbour": 10109,
  "harbour_depot": 10131,
  "repair_dock": 10132,
  "shield_generator_relocation": 10090,
  "anti_aircraft_site_relocation": 10224,
  "advanced_defence_turret_relocation": 10227,
  "harbour_defence_turret_relocation": 10254,
  "cargo": 50002,
  "cargo_large": 50064,
  "ark_relocation": 10069,
  "ark_ecos_relocation": 10233,
  "ark_tycoons_relocation": 10234,
  "ark_techs_relocation": 10235,
  "ark_father_techs_relocation": 10265,
  "ark_leaving": 10085,
  "ark_ecos_leaving": 10230,
  "ark_tycoons_leaving": 10231,
  "ark_techs_leaving": 10232,
  "ark_techs_father_leaving": 10266,
  "airfield_3x3": 10143,
  "airfield_3x6": 10144,
  "airfield_6x6": 10145,
  "headquarter_aquanauts": 10018,
  "aquanaut_props": 10146,
  "mine_green_offensive": 10111,
  "ozone_maker_green_offensive": 10205,
  "giant_pumping_station_oil_baron": 10062,
  "headquarter_oil_baron": 10115,
  "shipyard_tycoons_AI": 10135,
  "oil_baron_props": 10251,
  "harbour_pirates": 10133,
  "cannon_pirates": 10134,
  "cannon2_pirates": 10250,
  "pirates_props": 10252,
  "pirates_flotsam_props": 10253,
  "harbour_pirates_destroyed": 10258,
  "cannon_pirates_destroyed": 10259,
  "cannon2_pirates_destroyed": 10260,
  "scientist_academy": 10240,
  "town_center_supporter": 10040,
  "town_center_rival": 10263
};